name: Build CV PDF
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Compile LaTeX CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Commit PDF back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update CV PDF"
          file_pattern: "cv.pdf"